# Generated by Django 3.2.4 on 2021-07-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20210704_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
    ]
