# Generated by Django 3.2 on 2021-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_alter_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
