# Generated by Django 3.2.4 on 2021-07-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_auto_20210723_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['user', 'day', 'time']},
        ),
    ]
