# Generated by Django 3.2.4 on 2021-07-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_alter_group_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
    ]
